export const clientData = [
  {
    type: 'Person',
    name: 'João',
    lastname: 'Silva',
    gender: 'female',
    rg: '123456',
    cpf: '1234568945',
    cnpj: null,
    nationality: null,
    civil_status: 'single',
    capacity: 'relatively',
    profession: null,
    company: null,
    birth: '2020-02-02',
    mother_name: 'Joaquina',
    number_benefit: '843482151',
    status: 0,
    document: null,
    nit: null,
    inss_password: null,
    invalid_person: null,
    addresses: [
      {
        description: 'casa',
        zip_code: '79750000',
        street: 'Rua Um',
        number: 123,
        neighborhood: 'Centro',
        city: 'Nova Andradina',
        state: 'MS',
      },
      {
        description: 'Trabalho',
        zip_code: '79760000',
        street: 'Rua Dois',
        number: 456,
        neighborhood: 'Centro',
        city: 'Nova Alvorada',
        state: 'MS',
      },
    ],
    bank_accounts: [
      {
        bank: '269 - Nubank',
        state: 'Corrente',
        agency: '001',
        account: '1253',
        operation: null,
      },
    ],
    emails: [
      {
        email: 'admin@admin.com.br',
      },
      {
        email: 'admin_2@admin.com.br',
      },
    ],
    phones: [
      {
        phone: '67987654321',
      },
      {
        phone: '67963258741',
      },
    ],
  },
  {
    type: 'Person',
    name: 'João',
    lastname: 'Silva',
    gender: 'female',
    rg: '123456',
    cpf: '1234568945',
    cnpj: null,
    nationality: null,
    civil_status: 'single',
    capacity: 'relatively',
    profession: null,
    company: null,
    birth: '2020-02-02',
    mother_name: 'Joaquina',
    number_benefit: '843482151',
    status: 0,
    document: null,
    nit: null,
    inss_password: null,
    invalid_person: null,
    addresses: [
      {
        description: 'casa',
        zip_code: '79750000',
        street: 'Rua Um',
        number: 123,
        neighborhood: 'Centro',
        city: 'Nova Andradina',
        state: 'MS',
      },
      {
        description: 'Trabalho',
        zip_code: '79760000',
        street: 'Rua Dois',
        number: 456,
        neighborhood: 'Centro',
        city: 'Nova Alvorada',
        state: 'MS',
      },
    ],
    bank_accounts: [
      {
        bank: '269 - Nubank',
        state: 'Corrente',
        agency: '001',
        account: '1253',
        operation: null,
      },
    ],
    emails: [
      {
        email: 'admin@admin.com.br',
      },
      {
        email: 'admin_2@admin.com.br',
      },
    ],
    phones: [
      {
        phone: '67987654321',
      },
      {
        phone: '67963258741',
      },
    ],
  },
  {
    type: 'Person',
    name: 'João',
    lastname: 'Silva',
    gender: 'female',
    rg: '123456',
    cpf: '1234568945',
    cnpj: null,
    nationality: null,
    civil_status: 'single',
    capacity: 'relatively',
    profession: null,
    company: null,
    birth: '2020-02-02',
    mother_name: 'Joaquina',
    number_benefit: '843482151',
    status: 0,
    document: null,
    nit: null,
    inss_password: null,
    invalid_person: null,
    addresses: [
      {
        description: 'casa',
        zip_code: '79750000',
        street: 'Rua Um',
        number: 123,
        neighborhood: 'Centro',
        city: 'Nova Andradina',
        state: 'MS',
      },
      {
        description: 'Trabalho',
        zip_code: '79760000',
        street: 'Rua Dois',
        number: 456,
        neighborhood: 'Centro',
        city: 'Nova Alvorada',
        state: 'MS',
      },
    ],
    bank_accounts: [
      {
        bank: '269 - Nubank',
        state: 'Corrente',
        agency: '001',
        account: '1253',
        operation: null,
      },
    ],
    emails: [
      {
        email: 'admin@admin.com.br',
      },
      {
        email: 'admin_2@admin.com.br',
      },
    ],
    phones: [
      {
        phone: '67987654321',
      },
      {
        phone: '67963258741',
      },
    ],
  },
  {
    type: 'Person',
    name: 'João',
    lastname: 'Silva',
    gender: 'female',
    rg: '123456',
    cpf: '1234568945',
    cnpj: null,
    nationality: null,
    civil_status: 'single',
    capacity: 'relatively',
    profession: null,
    company: null,
    birth: '2020-02-02',
    mother_name: 'Joaquina',
    number_benefit: '843482151',
    status: 0,
    document: null,
    nit: null,
    inss_password: null,
    invalid_person: null,
    addresses: [
      {
        description: 'casa',
        zip_code: '79750000',
        street: 'Rua Um',
        number: 123,
        neighborhood: 'Centro',
        city: 'Nova Andradina',
        state: 'MS',
      },
      {
        description: 'Trabalho',
        zip_code: '79760000',
        street: 'Rua Dois',
        number: 456,
        neighborhood: 'Centro',
        city: 'Nova Alvorada',
        state: 'MS',
      },
    ],
    bank_accounts: [
      {
        bank: '269 - Nubank',
        state: 'Corrente',
        agency: '001',
        account: '1253',
        operation: null,
      },
    ],
    emails: [
      {
        email: 'admin@admin.com.br',
      },
      {
        email: 'admin_2@admin.com.br',
      },
    ],
    phones: [
      {
        phone: '67987654321',
      },
      {
        phone: '67963258741',
      },
    ],
  },
  {
    type: 'Person',
    name: 'João',
    lastname: 'Silva',
    gender: 'female',
    rg: '123456',
    cpf: '1234568945',
    cnpj: null,
    nationality: null,
    civil_status: 'single',
    capacity: 'relatively',
    profession: null,
    company: null,
    birth: '2020-02-02',
    mother_name: 'Joaquina',
    number_benefit: '843482151',
    status: 0,
    document: null,
    nit: null,
    inss_password: null,
    invalid_person: null,
    addresses: [
      {
        description: 'casa',
        zip_code: '79750000',
        street: 'Rua Um',
        number: 123,
        neighborhood: 'Centro',
        city: 'Nova Andradina',
        state: 'MS',
      },
      {
        description: 'Trabalho',
        zip_code: '79760000',
        street: 'Rua Dois',
        number: 456,
        neighborhood: 'Centro',
        city: 'Nova Alvorada',
        state: 'MS',
      },
    ],
    bank_accounts: [
      {
        bank: '269 - Nubank',
        state: 'Corrente',
        agency: '001',
        account: '1253',
        operation: null,
      },
    ],
    emails: [
      {
        email: 'admin@admin.com.br',
      },
      {
        email: 'admin_2@admin.com.br',
      },
    ],
    phones: [
      {
        phone: '67987654321',
      },
      {
        phone: '67963258741',
      },
    ],
  },
  {
    type: 'Person',
    name: 'João',
    lastname: 'Silva',
    gender: 'female',
    rg: '123456',
    cpf: '1234568945',
    cnpj: null,
    nationality: null,
    civil_status: 'single',
    capacity: 'relatively',
    profession: null,
    company: null,
    birth: '2020-02-02',
    mother_name: 'Joaquina',
    number_benefit: '843482151',
    status: 0,
    document: null,
    nit: null,
    inss_password: null,
    invalid_person: null,
    addresses: [
      {
        description: 'casa',
        zip_code: '79750000',
        street: 'Rua Um',
        number: 123,
        neighborhood: 'Centro',
        city: 'Nova Andradina',
        state: 'MS',
      },
      {
        description: 'Trabalho',
        zip_code: '79760000',
        street: 'Rua Dois',
        number: 456,
        neighborhood: 'Centro',
        city: 'Nova Alvorada',
        state: 'MS',
      },
    ],
    bank_accounts: [
      {
        bank: '269 - Nubank',
        state: 'Corrente',
        agency: '001',
        account: '1253',
        operation: null,
      },
    ],
    emails: [
      {
        email: 'admin@admin.com.br',
      },
      {
        email: 'admin_2@admin.com.br',
      },
    ],
    phones: [
      {
        phone: '67987654321',
      },
      {
        phone: '67963258741',
      },
    ],
  },
];
